stages:
  - build
  - trigger-helm

variables:
  DOCKER_IMAGE: hbn348/myapp
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA

build-java-app:
  image: docker:latest # Use Docker image with Docker CLI installed
  services:
    - docker:dind # Docker-in-Docker service
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - master

trigger-helm-pipeline:
  stage: trigger-helm
  trigger:
    project: JdidouBrahim/helm  # Helm repository project in GitLab
    branch: "main"  # Branch to trigger in the Helm repo
    strategy: depend  # Wait for the pipeline to finish
  only:
    - master
  variables:
    DOCKER_TAG: $DOCKER_TAG # Pass DOCKER_TAG to the downstream pipeline