stages:
  - build
  - update-helm-repo

variables:
  DOCKER_IMAGE: https://hub.docker.com/r/hbn348/myapp
  HELM_REPO: https://helm-18bc38.gitlab.io/

# Build the Docker image for the Java app
build-java-app:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - echo "Pushing Docker image to registry..."
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main

# Update Helm chart with the new image tag, package, and push to Helm repo
update-helm-repo:
  stage: update-helm-repo
  before_script:
    - apt-get update && apt-get install -y helm
  script:
    # Update values.yaml with the new Docker image tag
    - sed -i "s/tag:.*/tag: $CI_COMMIT_SHORT_SHA/" mychart/values.yaml
    - helm package mychart
    - helm repo index . --url $HELM_REPO
    # Push the updated chart and index.yaml to Helm repo
    - git config --global user.email "ci@automation.com"
    - git config --global user.name "CI Automation"
    - git add .
    - git commit -m "Update Helm chart for Java app version $CI_COMMIT_SHORT_SHA"
    - git push origin main
  only:
    - main
