stages:
  - build
  - update-helm-repo

variables:
  DOCKER_IMAGE: hbn348/myapp
  HELM_REPO: https://helm-18bc38.gitlab.io/my-helm-repo/
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA

# Build and push the Docker image to Docker Hub
build-java-app:
  image: docker:latest # Use Docker image with Docker CLI installed
  services:
    - docker:dind # Docker-in-Docker service
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - master

# Update the Helm chart with the new Docker image tag, package, and push to the Helm repository
update-helm-repo:
  stage: update-helm-repo
  image: bitnami/helm:3.9.0
  before_script:
    - apk update && apk add git
  script:
    # Print Helm version and help to debug issues
    - helm version
    - helm help
    # Update values.yaml with the new Docker image tag
    - |
      sed -i "s/tag:.*/tag: $DOCKER_TAG/" mychart/values.yaml
    # Package the Helm chart
    - helm package mychart
    # Update the index.yaml file for the Helm repo
    - helm repo index . --url $HELM_REPO
    # Commit and push the updated Helm chart and index.yaml
    - git config --global user.email "ci@automation.com"
    - git config --global user.name "CI Automation"
    - git add .
    - git commit -m "Update Helm chart for Java app version $DOCKER_TAG"
    - git push origin main
  only:
    - master