name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE: hbn348/myapp

jobs:
  build-java-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      - name: Set environment variables
        run: echo "DOCKER_IMAGE=hbn348/myapp" >> $GITHUB_ENV

      - name: Set GitHub SHA as DOCKER_TAG
        run: echo "DOCKER_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV


      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }}:$DOCKER_TAG .

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_IMAGE }}:$DOCKER_TAG

  trigger-helm-pipeline:
    runs-on: ubuntu-latest
    needs: build-java-app  # Ensure this job waits for the build-java-app job and uses its outputs
    steps:
      - name: Trigger Helm Pipeline
        env:
          DOCKER_TAG: ${GITHUB_SHA::7}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Docker tag is : $DOCKER_TAG"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $PERSONAL_ACCESS_TOKEN" \
            https://api.github.com/repos/JdidouBrahim/helm/actions/workflows/build-and-deploy.yml/dispatches \
            -d '{"ref":"main", "inputs": {"DOCKER_TAG": "'"$DOCKER_TAG"'"}}'
